# Fun Functions 

In this activity, you'll experiment with functions to produce a repeatable outcome. You'll use the sample data below for this activity.

In [ ]:
top_25_players = [{'Name': 'Cristiano Ronaldo',
  'Nationality': 'Portugal',
  'Club': 'Real Madrid',
  'Rating': 94,
  'Age': 32},
 {'Name': 'Lionel Messi',
  'Nationality': 'Argentina',
  'Club': 'FC Barcelona',
  'Rating': 93,
  'Age': 29},
 {'Name': 'Neymar',
  'Nationality': 'Brazil',
  'Club': 'FC Barcelona',
  'Rating': 92,
  'Age': 25},
 {'Name': 'Luis Suárez',
  'Nationality': 'Uruguay',
  'Club': 'FC Barcelona',
  'Rating': 92,
  'Age': 30},
 {'Name': 'Manuel Neuer',
  'Nationality': 'Germany',
  'Club': 'FC Bayern',
  'Rating': 92,
  'Age': 31},
 {'Name': 'De Gea',
  'Nationality': 'Spain',
  'Club': 'Manchester Utd',
  'Rating': 90,
  'Age': 26},
 {'Name': 'Robert Lewandowski',
  'Nationality': 'Poland',
  'Club': 'FC Bayern',
  'Rating': 90,
  'Age': 28},
 {'Name': 'Gareth Bale',
  'Nationality': 'Wales',
  'Club': 'Real Madrid',
  'Rating': 90,
  'Age': 27},
 {'Name': 'Zlatan Ibrahimović',
  'Nationality': 'Sweden',
  'Club': 'Manchester Utd',
  'Rating': 90,
  'Age': 35},
 {'Name': 'Thibaut Courtois',
  'Nationality': 'Belgium',
  'Club': 'Chelsea',
  'Rating': 89,
  'Age': 24},
 {'Name': 'Jérôme Boateng',
  'Nationality': 'Germany',
  'Club': 'FC Bayern',
  'Rating': 89,
  'Age': 28},
 {'Name': 'Eden Hazard',
  'Nationality': 'Belgium',
  'Club': 'Chelsea',
  'Rating': 89,
  'Age': 26},
 {'Name': 'Luka Modrić',
  'Nationality': 'Croatia',
  'Club': 'Real Madrid',
  'Rating': 89,
  'Age': 31},
 {'Name': 'Mesut Özil',
  'Nationality': 'Germany',
  'Club': 'Arsenal',
  'Rating': 89,
  'Age': 28},
 {'Name': 'Gonzalo Higuaín',
  'Nationality': 'Argentina',
  'Club': 'Juventus',
  'Rating': 89,
  'Age': 29},
 {'Name': 'Thiago Silva',
  'Nationality': 'Brazil',
  'Club': 'PSG',
  'Rating': 89,
  'Age': 32},
 {'Name': 'Sergio Ramos',
  'Nationality': 'Spain',
  'Club': 'Real Madrid',
  'Rating': 89,
  'Age': 31},
 {'Name': 'Sergio Agüero',
  'Nationality': 'Argentina',
  'Club': 'Manchester City',
  'Rating': 89,
  'Age': 28},
 {'Name': 'Paul Pogba',
  'Nationality': 'France',
  'Club': 'Manchester Utd',
  'Rating': 88,
  'Age': 24},
 {'Name': 'Antoine Griezmann',
  'Nationality': 'France',
  'Club': 'Atlético Madrid',
  'Rating': 88,
  'Age': 26},
 {'Name': 'Kevin De Bruyne',
  'Nationality': 'Belgium',
  'Club': 'Manchester City',
  'Rating': 88,
  'Age': 25},
 {'Name': 'Marco Reus',
  'Nationality': 'Germany',
  'Club': 'Bor. Dortmund',
  'Rating': 88,
  'Age': 27},
 {'Name': 'Alexis Sánchez',
  'Nationality': 'Chile',
  'Club': 'Arsenal',
  'Rating': 88,
  'Age': 28},
 {'Name': 'Toni Kroos',
  'Nationality': 'Germany',
  'Club': 'Real Madrid',
  'Rating': 88,
  'Age': 27},
 {'Name': 'Diego Godín',
  'Nationality': 'Uruguay',
  'Club': 'Atlético Madrid',
  'Rating': 88,
  'Age': 31}]

In [ ]:
bottom_25_players = [{'Name': 'Ben Kelly',
  'Nationality': 'Republic of Ireland',
  'Club': 'Dundalk',
  'Rating': 47,
  'Age': 19},
 {'Name': 'Kaylen Hinds',
  'Nationality': 'England',
  'Club': 'Stevenage',
  'Rating': 47,
  'Age': 19},
 {'Name': 'James King',
  'Nationality': 'England',
  'Club': 'Bradford City',
  'Rating': 47,
  'Age': 20},
 {'Name': 'Neil McLaughlin',
  'Nationality': 'Scotland',
  'Club': 'Partick Thistle',
  'Rating': 47,
  'Age': 19},
 {'Name': 'Nathan Clifford',
  'Nationality': 'Republic of Ireland',
  'Club': 'Finn Harps',
  'Rating': 46,
  'Age': 19},
 {'Name': 'Ciaran Kelly',
  'Nationality': 'Republic of Ireland',
  'Club': 'Finn Harps',
  'Rating': 46,
  'Age': 18},
 {'Name': 'Adam Kelsey',
  'Nationality': 'England',
  'Club': 'Scunthorpe Utd',
  'Rating': 46,
  'Age': 17},
 {'Name': 'Dominic Peppard',
  'Nationality': 'Republic of Ireland',
  'Club': 'Bohemian FC',
  'Rating': 46,
  'Age': 17},
 {'Name': 'Gavin Dowling',
  'Nationality': 'Republic of Ireland',
  'Club': 'Wexford Youths',
  'Rating': 46,
  'Age': 38},
 {'Name': 'Tommy Käßemodel',
  'Nationality': 'Germany',
  'Club': 'Erzgebirge Aue',
  'Rating': 46,
  'Age': 28},
 {'Name': 'Ronan Wilson',
  'Nationality': 'Northern Ireland',
  'Club': 'Derry City',
  'Rating': 46,
  'Age': 18},
 {'Name': 'Darragh Doherty',
  'Nationality': 'Republic of Ireland',
  'Club': 'Longford Town',
  'Rating': 46,
  'Age': 19},
 {'Name': 'Myles Judd',
  'Nationality': 'England',
  'Club': 'Leyton Orient',
  'Rating': 46,
  'Age': 18},
 {'Name': 'Sam Hornby',
  'Nationality': 'England',
  'Club': 'Burton Albion',
  'Rating': 46,
  'Age': 22},
 {'Name': 'Sam Sargeant',
  'Nationality': 'England',
  'Club': 'Leyton Orient',
  'Rating': 46,
  'Age': 19},
 {'Name': 'Steven Alzate',
  'Nationality': 'England',
  'Club': 'Leyton Orient',
  'Rating': 45,
  'Age': 18},
 {'Name': 'Sam Dalby',
  'Nationality': 'England',
  'Club': 'Leyton Orient',
  'Rating': 45,
  'Age': 17},
 {'Name': 'Henry Ochieng',
  'Nationality': 'England',
  'Club': 'Leyton Orient',
  'Rating': 45,
  'Age': 18},
 {'Name': 'Harry Clifton',
  'Nationality': 'England',
  'Club': 'Grimsby Town',
  'Rating': 45,
  'Age': 18},
 {'Name': 'Mark McElhinney',
  'Nationality': 'Republic of Ireland',
  'Club': 'Derry City',
  'Rating': 45,
  'Age': 19},
 {'Name': 'Adam Dunbar',
  'Nationality': 'Republic of Ireland',
  'Club': 'Wexford Youths',
  'Rating': 45,
  'Age': 19},
 {'Name': 'Dylan McGoey',
  'Nationality': 'Republic of Ireland',
  'Club': 'Longford Town',
  'Rating': 45,
  'Age': 19},
 {'Name': 'Tommy Ouldridge',
  'Nationality': 'England',
  'Club': 'Swindon Town',
  'Rating': 45,
  'Age': 18},
 {'Name': 'Mark Foden',
  'Nationality': 'Scotland',
  'Club': 'Ross County',
  'Rating': 45,
  'Age': 21},
 {'Name': 'Barry Richardson',
  'Nationality': 'England',
  'Club': 'Wycombe',
  'Rating': 45,
  'Age': 47}]

## Task 1: 

Question: Does the age of a player affect a player's ratings? 

To answer this question, find the average age of the top and bottom 25 players in the world. 

How? 
1. Create a function that takes in a list of players as the input, and returns the average age of all players in the supplied list 
2. Inside of the function, you'll create a for loop to iterate through all players in the list 
3. Inside of the loop,  you'll sum all the player's age 
4. Outside of the loop, you'll get the total number of players by taking length of the list using the `len()` function: https://www.w3schools.com/python/ref_func_len.asp
5. Outside of the loop, calculate the average by taking `Sum of all players ages` / `Total number of players` 
6. Finally, invoke your function by passing in a list of all players

In [ ]:
# create your function here

In [ ]:
# get the average age of the top 25 players and print the result 

# get the average age of the bottom 25 players and print the result

## Task 2: 

Question: What are the best and worst clubs? 

To answer this question, find the average rating of clubs for the top 25 and bottom 25 players of the world. 

How? 
1. Like before, create a function that accepts a list of players 
2. Create a new dictionary to calculate the `total rating` for each club. You'll need to create new key-value pairs if the key does not exist. 
3. Create a new dictionary to calculate the `total number of players` for each club. You'll need to create new key-value pairs if the key does not exist. 
4. Create a new dictionary to store the average club rating by taking `total rating` / `total number of players` in each club. 

Hint: This question requires the use of `.get()` on a dictionary.

In [ ]:
# create your function here

In [ ]:
# get the average rating for the top clubs and print the result 

# get the average rating for the bottom clubs and print the result